In [1]:
import pandas as pd
import numpy as np

## Global Domain Data

In [2]:
covid_global_domain_cum_data = pd.read_csv('F:/Pandemic-Database/Raw_Data/Covid 19/time_series_covid19_confirmed_global.csv')

covid_global_domain_cum_data = covid_global_domain_cum_data.rename(columns={'Country/Region':'Country',
                                                                           'Province/State':'Domain',})

covid_global_domain_cum_data = covid_global_domain_cum_data.drop(columns=['Lat','Long'])

data_columns = covid_global_domain_cum_data.columns[2:]

covid_global_domain_cum_data = pd.melt(covid_global_domain_cum_data, 
                                       id_vars=['Domain','Country'],
                                       value_vars=data_columns,
                                       var_name = 'date',
                                       value_name='number')

covid_global_domain_cum_data = covid_global_domain_cum_data[['Country','Domain','date','number']]

covid_global_domain_cum_data.insert(0,'Microbe Family','Coronaviridae')
covid_global_domain_cum_data.insert(1,'Microbe Genus','Betacoronavirus')
covid_global_domain_cum_data.insert(2,'Microbe Species','SARS-CoV-2')
covid_global_domain_cum_data.insert(3,'Region',np.nan)
covid_global_domain_cum_data.insert(6,'Sub-Domain',np.nan)
covid_global_domain_cum_data.insert(8,'type','Cumulative_Cases')

covid_global_domain_cum_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,Domain,Sub-Domain,date,type,number
0,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,Afghanistan,NaN,NaN,1/22/20,Cumulative_Cases,0
1,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,Albania,NaN,NaN,1/22/20,Cumulative_Cases,0
2,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,Algeria,NaN,NaN,1/22/20,Cumulative_Cases,0
3,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,Andorra,NaN,NaN,1/22/20,Cumulative_Cases,0
4,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,Angola,NaN,NaN,1/22/20,Cumulative_Cases,0
...,...,...,...,...,...,...,...,...,...,...
330322,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,West Bank and Gaza,NaN,NaN,3/9/23,Cumulative_Cases,703228
330323,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,Winter Olympics 2022,NaN,NaN,3/9/23,Cumulative_Cases,535
330324,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,Yemen,NaN,NaN,3/9/23,Cumulative_Cases,11945
330325,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,Zambia,NaN,NaN,3/9/23,Cumulative_Cases,343135
330326,Coronaviridae,Betacoronavirus,SARS-CoV-2,NaN,Zimbabwe,NaN,NaN,3/9/23,Cumulative_Cases,264276

In [4]:
country_to_region_dict = np.load('F:/Pandemic-Database/Internal/Intermediate_Data_Archive/Country_Region_Dict.npy',
                                 allow_pickle=True).item()

country_to_region_dict.update({'Burma':'SEARO',
'Cabo Verde':'AFRO',
'Congo (Brazzaville)':'AFRO',
'Congo (Kinshasa)':'AFRO',
"Cote d'Ivoire":'AFRO',
'Czechia':'EURO',
'Holy See':'EURO',
'Korea, North':'SEARO',
'Korea, South':'WPRO',
'Kosovo':'EURO',
'Liechtenstein':'EURO',
'Sao Tome and Principe':'AFRO',
'Taiwan*':'WPRO',
'US':'AMRO'})

covid_global_domain_cum_data['Region'] = covid_global_domain_cum_data['Country'].map(country_to_region_dict)

covid_global_domain_cum_data = covid_global_domain_cum_data.dropna(subset='Region')

covid_global_domain_cum_data['Country'] = covid_global_domain_cum_data['Country'].replace('US','United States')

covid_global_domain_cum_data

C:\Users\Ziming Wei\AppData\Local\Temp\ipykernel_33156\236046269.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_global_domain_cum_data['Country'] = covid_global_domain_cum_data['Country'].replace('US','United States')

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,Domain,Sub-Domain,date,type,number
0,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,Afghanistan,NaN,NaN,1/22/20,Cumulative_Cases,0
1,Coronaviridae,Betacoronavirus,SARS-CoV-2,EURO,Albania,NaN,NaN,1/22/20,Cumulative_Cases,0
2,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Algeria,NaN,NaN,1/22/20,Cumulative_Cases,0
3,Coronaviridae,Betacoronavirus,SARS-CoV-2,EURO,Andorra,NaN,NaN,1/22/20,Cumulative_Cases,0
4,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Angola,NaN,NaN,1/22/20,Cumulative_Cases,0
...,...,...,...,...,...,...,...,...,...,...
330320,Coronaviridae,Betacoronavirus,SARS-CoV-2,AMRO,Venezuela,NaN,NaN,3/9/23,Cumulative_Cases,552162
330321,Coronaviridae,Betacoronavirus,SARS-CoV-2,WPRO,Vietnam,NaN,NaN,3/9/23,Cumulative_Cases,11526994
330324,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,Yemen,NaN,NaN,3/9/23,Cumulative_Cases,11945
330325,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Zambia,NaN,NaN,3/9/23,Cumulative_Cases,343135
330326,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Zimbabwe,NaN,NaN,3/9/23,Cumulative_Cases,264276

In [5]:
covid_global_domain_cum_data = covid_global_domain_cum_data[~covid_global_domain_cum_data['Domain'].isna()]
covid_global_domain_cum_data['date'] = pd.to_datetime(covid_global_domain_cum_data['date'],format="%m/%d/%y")
covid_global_domain_cum_data

C:\Users\Ziming Wei\AppData\Local\Temp\ipykernel_33156\2501864338.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_global_domain_cum_data['date'] = pd.to_datetime(covid_global_domain_cum_data['date'],format="%m/%d/%y")

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,Domain,Sub-Domain,date,type,number
9,Coronaviridae,Betacoronavirus,SARS-CoV-2,WPRO,Australia,Australian Capital Territory,NaN,2020-01-22,Cumulative_Cases,0
10,Coronaviridae,Betacoronavirus,SARS-CoV-2,WPRO,Australia,New South Wales,NaN,2020-01-22,Cumulative_Cases,0
11,Coronaviridae,Betacoronavirus,SARS-CoV-2,WPRO,Australia,Northern Territory,NaN,2020-01-22,Cumulative_Cases,0
12,Coronaviridae,Betacoronavirus,SARS-CoV-2,WPRO,Australia,Queensland,NaN,2020-01-22,Cumulative_Cases,0
13,Coronaviridae,Betacoronavirus,SARS-CoV-2,WPRO,Australia,South Australia,NaN,2020-01-22,Cumulative_Cases,0
...,...,...,...,...,...,...,...,...,...,...
330311,Coronaviridae,Betacoronavirus,SARS-CoV-2,EURO,United Kingdom,Jersey,NaN,2023-03-09,Cumulative_Cases,66391
330312,Coronaviridae,Betacoronavirus,SARS-CoV-2,EURO,United Kingdom,Montserrat,NaN,2023-03-09,Cumulative_Cases,1403
330313,Coronaviridae,Betacoronavirus,SARS-CoV-2,EURO,United Kingdom,Pitcairn Islands,NaN,2023-03-09,Cumulative_Cases,4
330314,Coronaviridae,Betacoronavirus,SARS-CoV-2,EURO,United Kingdom,"Saint Helena, Ascension and Tristan da Cunha",NaN,2023-03-09,Cumulative_Cases,2166
330315,Coronaviridae,Betacoronavirus,SARS-CoV-2,EURO,United Kingdom,Turks and Caicos Islands,NaN,2023-03-09,Cumulative_Cases,6561

## US Domain Data

In [6]:
us_domain_data = pd.read_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Covid 19/Covid_US_Daily_CumCases.csv')
us_domain_data = us_domain_data.rename(columns={'State/City':'Domain'})
us_domain_data.insert(7,'Sub-Domain',np.nan)

us_domain_data = us_domain_data[['Microbe Family', 'Microbe Genus', 'Microbe Species', 'Region', 'Country', 'Domain', 'Sub-Domain','date', 'type', 'number']]
us_domain_data['date'] = pd.to_datetime(us_domain_data['date'])
us_domain_data

FileNotFoundError: [Errno 2] No such file or directory: 'F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Covid 19/Covid_US_Daily_CumCases.csv'

## World Country Data

In [102]:
world_country_level_data = pd.read_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Covid 19/Covid_World_Daily_CumCases.csv')
world_country_level_data.insert(6,'Sub-Domain',np.nan)
world_country_level_data = world_country_level_data.rename(columns={'State/City':'Domain'})
world_country_level_data['date'] = pd.to_datetime(world_country_level_data['date'])
world_country_level_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,Domain,Sub-Domain,date,type,number
0,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,Afghanistan,NaN,NaN,2020-01-03,Cumulative_Cases,0
1,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,Afghanistan,NaN,NaN,2020-01-04,Cumulative_Cases,0
2,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,Afghanistan,NaN,NaN,2020-01-05,Cumulative_Cases,0
3,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,Afghanistan,NaN,NaN,2020-01-06,Cumulative_Cases,0
4,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,Afghanistan,NaN,NaN,2020-01-07,Cumulative_Cases,0
...,...,...,...,...,...,...,...,...,...,...
329899,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Zimbabwe,NaN,NaN,2023-10-21,Cumulative_Cases,265821
329900,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Zimbabwe,NaN,NaN,2023-10-22,Cumulative_Cases,265821
329901,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Zimbabwe,NaN,NaN,2023-10-23,Cumulative_Cases,265821
329902,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Zimbabwe,NaN,NaN,2023-10-24,Cumulative_Cases,265821
329903,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Zimbabwe,NaN,NaN,2023-10-25,Cumulative_Cases,265821

## Merge Data

In [105]:
covid_full_data = pd.concat([covid_global_domain_cum_data,us_domain_data,world_country_level_data]).sort_values(by=['date','Country','Domain','Sub-Domain'])

covid_full_data = covid_full_data.reset_index(drop=True)

covid_full_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,Domain,Sub-Domain,date,type,number
0,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,Afghanistan,NaN,NaN,2020-01-03,Cumulative_Cases,0
1,Coronaviridae,Betacoronavirus,SARS-CoV-2,EURO,Albania,NaN,NaN,2020-01-03,Cumulative_Cases,0
2,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Algeria,NaN,NaN,2020-01-03,Cumulative_Cases,0
3,Coronaviridae,Betacoronavirus,SARS-CoV-2,WPRO,American Samoa,NaN,NaN,2020-01-03,Cumulative_Cases,0
4,Coronaviridae,Betacoronavirus,SARS-CoV-2,EURO,Andorra,NaN,NaN,2020-01-03,Cumulative_Cases,0
...,...,...,...,...,...,...,...,...,...,...
495854,Coronaviridae,Betacoronavirus,SARS-CoV-2,WPRO,Wallis and Futuna,NaN,NaN,2023-10-25,Cumulative_Cases,3550
495855,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,Yemen,NaN,NaN,2023-10-25,Cumulative_Cases,11945
495856,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Zambia,NaN,NaN,2023-10-25,Cumulative_Cases,349287
495857,Coronaviridae,Betacoronavirus,SARS-CoV-2,AFRO,Zimbabwe,NaN,NaN,2023-10-25,Cumulative_Cases,265821
495858,Coronaviridae,Betacoronavirus,SARS-CoV-2,EMRO,"occupied Palestinian territory, including east...",NaN,NaN,2023-10-25,Cumulative_Cases,703228

In [106]:
covid_full_data.to_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Covid 19/Covid_World_Domain_Daily_CumCases.csv',
                      index = False)

In [20]:
a = pd.read_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Covid 19/Covid_World_Domain_Daily_CumCases.csv')

set(a['Domain'])

C:\Users\Ziming Wei\AppData\Local\Temp\ipykernel_33156\3690138061.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  a = pd.read_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Covid 19/Covid_World_Domain_Daily_CumCases.csv')

{'Xinjiang',
 'British Columbia',
 'British Virgin Islands',
 'Western Australia',
 'French Polynesia',
 'Utah',
 'Oklahoma',
 'Delaware',
 'Liaoning',
 'Inner Mongolia',
 'Unknown',
 'Yunnan',
 'Saskatchewan',
 'Arkansas',
 'Sichuan',
 'Connecticut',
 'Ohio',
 'Jersey',
 'Tianjin',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'St Martin',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 ...}