In [1]:
import pandas as pd 
import numpy as np

In [5]:
ebola_data = pd.read_csv('F:/Pandemic-Database/Raw_Data/Ebola/Ebola_CDC_Confirmed_and_Death_Clean_Data.csv')
ebola_data

,Virus Family,Virus Genus,Virus Species,Region,Sub-region,Date,Type,Case Number,Comments
0,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Guinea,2014-03-25,Confirmed,86,NaN
1,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Guinea,2014-03-25,Deaths,59,NaN
2,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Guinea,2014-03-26,Confirmed,86,NaN
3,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Guinea,2014-03-26,Deaths,60,NaN
4,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Guinea,2014-03-27,Confirmed,103,NaN
...,...,...,...,...,...,...,...,...,...
1585,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Sierra Leone,2016-03-23,Deaths,3956,NaN
1586,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Sierra Leone,2016-03-30,Confirmed,14124,NaN
1587,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Sierra Leone,2016-03-30,Deaths,3956,NaN
1588,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Sierra Leone,2016-04-13,Confirmed,14124,NaN
1589,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,Africa,Sierra Leone,2016-04-13,Deaths,3956,NaN

### Guinea Data

In [24]:
guinea_confirmed_data = ebola_data[(ebola_data['Sub-region'] == ' Guinea') & (ebola_data['Type'] == 'Confirmed')]
guinea_confirmed_data = guinea_confirmed_data.reset_index(drop = True)
guinea_confirmed_data = guinea_confirmed_data.rename(columns= {'Virus Family':'Microbe Family',
                                                     'Virus Genus': 'Microbe Genus',
                                                     'Virus Species': 'Microbe Species',
                                                     'Sub-region': 'Country',
                                                     'Type': 'type',
                                                     'Date': 'date',
                                                     'Case Number': 'number'})
guinea_confirmed_data.insert(5, 'State/City', 'None')
guinea_confirmed_data['type'] = 'CumCases'
guinea_confirmed_data['Region'] = 'AFRO'
guinea_confirmed_data = guinea_confirmed_data.drop(columns='Comments')
guinea_confirmed_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,State/City,date,type,number
0,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-03-25,CumCases,86
1,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-03-26,CumCases,86
2,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-03-27,CumCases,103
3,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-03-31,CumCases,112
4,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-04-01,CumCases,122
...,...,...,...,...,...,...,...,...,...
260,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-02-17,CumCases,3804
261,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-03-03,CumCases,3804
262,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-03-23,CumCases,3809
263,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-03-30,CumCases,3811
264,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-04-13,CumCases,3814

In [26]:
guinea_confirmed_data.to_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Ebola/Ebola_Guinea_Weekly_CumCases.csv',
                            index = False)

In [29]:
guinea_case_data = guinea_confirmed_data.copy()
guinea_case_data['Case_diff'] = guinea_case_data['number'].diff()
guinea_case_data = guinea_case_data[guinea_case_data['Case_diff'] >= 0]
guinea_case_data = guinea_case_data.reset_index(drop = True)
guinea_case_data['number'] = guinea_case_data['Case_diff']
guinea_case_data['type'] = 'Cases'
guinea_case_data['Region'] = 'AFRO'
guinea_case_data = guinea_case_data.drop(columns='Case_diff')
guinea_case_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,State/City,date,type,number
0,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-03-26,Cases,0.0
1,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-03-27,Cases,17.0
2,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-03-31,Cases,9.0
3,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-04-01,Cases,10.0
4,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2014-04-02,Cases,5.0
...,...,...,...,...,...,...,...,...,...
210,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-02-17,Cases,0.0
211,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-03-03,Cases,0.0
212,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-03-23,Cases,5.0
213,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-03-30,Cases,2.0
214,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Guinea,None,2016-04-13,Cases,3.0

In [30]:
guinea_case_data.to_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Ebola/Ebola_Guinea_Weekly_Cases.csv',
                        index = False)

### Sierra Leone Data

In [27]:
sl_confirmed_data = ebola_data[(ebola_data['Sub-region'] == ' Sierra Leone') & (ebola_data['Type'] == 'Confirmed')]
sl_confirmed_data = sl_confirmed_data.reset_index(drop = True)
sl_confirmed_data = sl_confirmed_data.rename(columns= {'Virus Family':'Microbe Family',
                                                     'Virus Genus': 'Microbe Genus',
                                                     'Virus Species': 'Microbe Species',
                                                     'Sub-region': 'Country',
                                                     'Type': 'type',
                                                     'Date': 'date',
                                                     'Case Number': 'number'})
sl_confirmed_data.insert(5, 'State/City', 'None')
sl_confirmed_data['type'] = 'CumCases'
sl_confirmed_data['Region'] = 'AFRO'
sl_confirmed_data = sl_confirmed_data.drop(columns='Comments')
sl_confirmed_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,State/City,date,type,number
0,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-03-25,CumCases,0
1,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-03-26,CumCases,0
2,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-03-27,CumCases,6
3,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-03-31,CumCases,0
4,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-04-01,CumCases,0
...,...,...,...,...,...,...,...,...,...
260,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-02-17,CumCases,14124
261,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-03-03,CumCases,14124
262,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-03-23,CumCases,14124
263,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-03-30,CumCases,14124
264,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-04-13,CumCases,14124

In [28]:
sl_confirmed_data.to_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Ebola/Ebola_SierraLeone_Weekly_CumCases.csv',
                         index = False)

In [33]:
sl_case_data = sl_confirmed_data.copy()
sl_case_data['Case_diff'] = sl_case_data['number'].diff()
sl_case_data = sl_case_data[sl_case_data['Case_diff'] >= 0]
sl_case_data = sl_case_data.reset_index(drop = True)
sl_case_data['number'] = sl_case_data['Case_diff']
sl_case_data['type'] = 'Cases'
sl_case_data['Region'] = 'AFRO'
sl_case_data = sl_case_data.drop(columns='Case_diff')
sl_case_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,State/City,date,type,number
0,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-03-26,Cases,0.0
1,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-03-27,Cases,6.0
2,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-04-01,Cases,0.0
3,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-04-02,Cases,0.0
4,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2014-04-07,Cases,0.0
...,...,...,...,...,...,...,...,...,...
251,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-02-17,Cases,0.0
252,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-03-03,Cases,0.0
253,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-03-23,Cases,0.0
254,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-03-30,Cases,0.0
255,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Sierra Leone,None,2016-04-13,Cases,0.0

In [34]:
sl_case_data.to_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Ebola/Ebola_SierraLeone_Weekly_Cases.csv',
                    index = False)

###  Liberia Data

In [35]:
liberia_confirmed_data = ebola_data[(ebola_data['Sub-region'] == ' Liberia') & (ebola_data['Type'] == 'Confirmed')]
liberia_confirmed_data = liberia_confirmed_data.reset_index(drop = True)
liberia_confirmed_data = liberia_confirmed_data.rename(columns= {'Virus Family':'Microbe Family',
                                                     'Virus Genus': 'Microbe Genus',
                                                     'Virus Species': 'Microbe Species',
                                                     'Sub-region': 'Country',
                                                     'Type': 'type',
                                                     'Date': 'date',
                                                     'Case Number': 'number'})
liberia_confirmed_data.insert(5, 'State/City', 'None')
liberia_confirmed_data['type'] = 'CumCases'
liberia_confirmed_data['Region'] = 'AFRO'
liberia_confirmed_data = liberia_confirmed_data.drop(columns='Comments')
liberia_confirmed_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,State/City,date,type,number
0,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-03-25,CumCases,0
1,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-03-26,CumCases,0
2,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-03-27,CumCases,8
3,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-03-31,CumCases,8
4,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-04-01,CumCases,8
...,...,...,...,...,...,...,...,...,...
260,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-02-17,CumCases,10675
261,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-03-03,CumCases,10675
262,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-03-23,CumCases,10675
263,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-03-30,CumCases,10675
264,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-04-13,CumCases,10678

In [36]:
liberia_confirmed_data.to_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Ebola/Ebola_Liberia_Weekly_CumCases.csv',
                              index = False)

In [37]:
liberia_case_data = liberia_confirmed_data.copy()
liberia_case_data['Case_diff'] = liberia_case_data['number'].diff()
liberia_case_data = liberia_case_data[liberia_case_data['Case_diff'] >= 0]
liberia_case_data = liberia_case_data.reset_index(drop = True)
liberia_case_data['number'] = liberia_case_data['Case_diff']
liberia_case_data['type'] = 'Cases'
liberia_case_data['Region'] = 'AFRO'
liberia_case_data = liberia_case_data.drop(columns='Case_diff')
liberia_case_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,State/City,date,type,number
0,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-03-26,Cases,0.0
1,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-03-27,Cases,8.0
2,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-03-31,Cases,0.0
3,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-04-01,Cases,0.0
4,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2014-04-02,Cases,0.0
...,...,...,...,...,...,...,...,...,...
250,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-02-17,Cases,0.0
251,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-03-03,Cases,0.0
252,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-03-23,Cases,0.0
253,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-03-30,Cases,0.0
254,Filoviridae,Ebolavirus,Ebola Virus/ Sudan Virus/ Tai Forest Virus/ Bu...,AFRO,Liberia,None,2016-04-13,Cases,3.0

In [38]:
liberia_case_data.to_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Ebola/Ebola_Liberia_Weekly_Cases.csv',
                    index = False)