In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

### US Data

In [9]:
ilinet_data = pd.read_csv('F:/Pandemic-Database/Raw_Data/Influenza/ILINet.csv',
                         header= 1)
ilinet_data = ilinet_data

,REGION TYPE,REGION,YEAR,WEEK,% WEIGHTED ILI,%UNWEIGHTED ILI,AGE 0-4,AGE 25-49,AGE 25-64,AGE 5-24,AGE 50-64,AGE 65,ILITOTAL,NUM. OF PROVIDERS,TOTAL PATIENTS
0,National,X,1997,40,1.10148,1.21686,179,X,157,205,X,29,570,192,46842
1,National,X,1997,41,1.20007,1.28064,199,X,151,242,X,23,615,191,48023
2,National,X,1997,42,1.37876,1.23906,228,X,153,266,X,34,681,219,54961
3,National,X,1997,43,1.19920,1.14473,188,X,193,236,X,36,653,213,57044
4,National,X,1997,44,1.65618,1.26112,217,X,162,280,X,41,700,213,55506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342,National,X,2023,25,1.37277,1.44777,6997,8722,X,8934,3233,2983,30869,3554,2132179
1343,National,X,2023,26,1.28216,1.32801,6388,8126,X,8008,3041,2910,28473,3505,2144029
1344,National,X,2023,27,1.23907,1.29281,5931,7456,X,7461,2935,2813,26596,3474,2057223
1345,National,X,2023,28,1.16642,1.20600,5579,7553,X,7020,2911,2756,25819,3433,2140887
1346,National,X,2023,29,1.12795,1.19575,5600,7398,X,6722,2891,2793,25404,3389,2124530

### World Data

In [2]:
world_ilinet_data = pd.read_csv('F:/Pandemic-Database/Raw_Data/Influenza/WHO_influenza.csv')
world_ilinet_data = world_ilinet_data.dropna(subset=['Cases of influenza-like illnesses'])
world_ilinet_data = world_ilinet_data[['Country','Day','Cases of influenza-like illnesses']]
world_ilinet_data = world_ilinet_data.reset_index(drop = True)
world_ilinet_data.insert(0,'Microbe Family','Orthomyxovididae')
world_ilinet_data.insert(1,'Microbe Genus','Influenza A, B, and C Virus')
world_ilinet_data.insert(2,'Microbe Species', 'None' )
world_ilinet_data.insert(3,'Region', 'None' )
world_ilinet_data.insert(6,'State/City', 'None')
world_ilinet_data.insert(7,'type', 'Cases')

world_ilinet_data = world_ilinet_data.rename(columns={'Day':'date',
                                                      'Cases of influenza-like illnesses': 'number'})

world_ilinet_data

,Microbe Family,Microbe Genus,Microbe Species,Region,Country,date,State/City,type,number
0,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Afghanistan,2016-03-14,None,Cases,494.0
1,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Afghanistan,2016-03-21,None,Cases,715.0
2,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Afghanistan,2016-03-28,None,Cases,704.0
3,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Afghanistan,2016-04-04,None,Cases,749.0
4,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Afghanistan,2016-04-11,None,Cases,651.0
...,...,...,...,...,...,...,...,...,...
68349,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Zambia,2021-11-29,None,Cases,1866.0
68350,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Zambia,2021-12-06,None,Cases,1394.0
68351,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Zambia,2021-12-13,None,Cases,1348.0
68352,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Zambia,2021-12-20,None,Cases,1513.0
68353,Orthomyxovididae,"Influenza A, B, and C Virus",None,None,Zambia,2021-12-27,None,Cases,1641.0

In [33]:
world_ilinet_data.to_csv('F:/Pandemic-Database/Past_Pandemic_Time_Series_Data/Influenza/Influenza_World_Weekly_Cases.csv',
                        index = False)

In [8]:
world_ilinet_data['date'].min()

'2009-01-05'

In [9]:
world_ilinet_data['date'].max()

'2023-10-09'