In [40]:
import pandas as pd
import numpy as np

## Covid-19

In [56]:
covid_data = pd.read_csv('F:/Pandemic-Database/Processed_Time_Series_Data/Covid_19/Covid_World_Domain_Daily_CumCases.csv')
covid_data['Year'] = pd.DatetimeIndex(covid_data['date']).year
covid_meta_data = covid_data[['Region','Year','Country','Domain','Sub-Domain']]
covid_meta_data = covid_meta_data.drop_duplicates()
covid_meta_data

C:\Users\Ziming Wei\AppData\Local\Temp\ipykernel_34192\3285420494.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  covid_data = pd.read_csv('F:/Pandemic-Database/Processed_Time_Series_Data/Covid_19/Covid_World_Domain_Daily_CumCases.csv')

,Region,Year,Country,Domain,Sub-Domain
0,EMRO,2020,Afghanistan,NaN,NaN
1,EURO,2020,Albania,NaN,NaN
2,AFRO,2020,Algeria,NaN,NaN
3,WPRO,2020,American Samoa,NaN,NaN
4,EURO,2020,Andorra,NaN,NaN
...,...,...,...,...,...
414832,WPRO,2023,Wallis and Futuna,NaN,NaN
414833,EMRO,2023,Yemen,NaN,NaN
414834,AFRO,2023,Zambia,NaN,NaN
414835,AFRO,2023,Zimbabwe,NaN,NaN
414836,EMRO,2023,"occupied Palestinian territory, including east...",NaN,NaN

In [57]:
Covid_LoS_dict_low = {'AMRO':15.70,
                 'EURO':9.03,
                 'AMRO':11.45,
                 'EMRO':8.26,
                 'AFRO':1.00,
                 'WPRO':15.70,
                 'SEARO':15.70,
                 'Other':5.96}

Covid_LoS_dict_high = {'AMRO':21.12,
                 'EURO':21.59,
                 'AMRO':26.91,
                 'EMRO':15.60,
                 'AFRO':22.76,
                 'WPRO':21.12,
                 'SEARO':21.12,
                 'Other':21.38}

covid_meta_data['LoS_mean'] = np.nan

covid_meta_data['LoS_low'] = covid_meta_data['Region'].map(Covid_LoS_dict_low)
covid_meta_data['LoS_high'] = covid_meta_data['Region'].map(Covid_LoS_dict_high)

covid_meta_data.insert(0,'Pandemic', 'Covid-19')

covid_meta_data['mortality_rate'] = 0.011
covid_meta_data['hopitalization_rate_mean'] = 0.048
covid_meta_data['hopitalization_rate_low'] = 0.004
covid_meta_data['hopitalization_rate_high'] = 0.092
covid_meta_data['R0_mean'] = np.nan
covid_meta_data['R0_low'] = 1.4 
covid_meta_data['R0_high'] = 6.49
covid_meta_data['Object_Transmit'] = 1
covid_meta_data['Blood_Transmit'] = 0
covid_meta_data['Airborne'] = 1
covid_meta_data['Vector_Transmit'] = 0
covid_meta_data['Droplets_Transmit'] = 1
covid_meta_data['latent_period_mean'] = 5.5
covid_meta_data['latent_period_low'] = 5.1
covid_meta_data['latent_period_high'] = 5.9
covid_meta_data['incubation_period_mean'] = 6.9
covid_meta_data['incubation_period_low'] = 6.3
covid_meta_data['incubation_period_high'] = 7.5
covid_meta_data['average_time_to_death_mean'] = np.nan
covid_meta_data['average_time_to_death_low'] = 2
covid_meta_data['average_time_to_death_high'] = 10
covid_meta_data['average_time_to_discharge_mean'] = np.nan
covid_meta_data['average_time_to_discharge_low'] = np.nan
covid_meta_data['average_time_to_discharge_high'] = np.nan

covid_meta_data

,Pandemic,Region,Year,Country,Domain,Sub-Domain,LoS_mean,LoS_low,LoS_high,mortality_rate,...,latent_period_high,incubation_period_mean,incubation_period_low,incubation_period_high,average_time_to_death_mean,average_time_to_death_low,average_time_to_death_high,average_time_to_discharge_mean,average_time_to_discharge_low,average_time_to_discharge_high
0,Covid-19,EMRO,2020,Afghanistan,NaN,NaN,NaN,8.26,15.60,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN
1,Covid-19,EURO,2020,Albania,NaN,NaN,NaN,9.03,21.59,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN
2,Covid-19,AFRO,2020,Algeria,NaN,NaN,NaN,1.00,22.76,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN
3,Covid-19,WPRO,2020,American Samoa,NaN,NaN,NaN,15.70,21.12,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN
4,Covid-19,EURO,2020,Andorra,NaN,NaN,NaN,9.03,21.59,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414832,Covid-19,WPRO,2023,Wallis and Futuna,NaN,NaN,NaN,15.70,21.12,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN
414833,Covid-19,EMRO,2023,Yemen,NaN,NaN,NaN,8.26,15.60,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN
414834,Covid-19,AFRO,2023,Zambia,NaN,NaN,NaN,1.00,22.76,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN
414835,Covid-19,AFRO,2023,Zimbabwe,NaN,NaN,NaN,1.00,22.76,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN
414836,Covid-19,EMRO,2023,"occupied Palestinian territory, including east...",NaN,NaN,NaN,8.26,15.60,0.011,...,5.9,6.9,6.3,7.5,NaN,2,10,NaN,NaN,NaN

## Dengue

In [58]:
dengue_data = pd.read_csv('F:/Pandemic-Database/Processed_Time_Series_Data/Dengue_Fever/Dengue_AMRO_Country_Weekly_CumCases.csv')

dengue_data['Year'] = pd.DatetimeIndex(dengue_data['date']).year
dengue_meta_data = dengue_data[['Region','Year','Country','Domain','Sub-Domain']]
dengue_meta_data = dengue_meta_data.drop_duplicates()

dengue_meta_data.insert(0,'Pandemic', 'Dengue')

dengue_meta_data['LoS_mean'] = 3.46
dengue_meta_data['LoS_low'] = 0.01
dengue_meta_data['LoS_high'] = 6.91
dengue_meta_data['mortality_rate'] = 0.2
dengue_meta_data['hopitalization_rate_mean'] = 0.324
dengue_meta_data['hopitalization_rate_low'] = np.nan
dengue_meta_data['hopitalization_rate_high'] = np.nan
dengue_meta_data['R0_mean'] = 27.2
dengue_meta_data['R0_low'] = 14.8
dengue_meta_data['R0_high'] = 49.3
dengue_meta_data['Object_Transmit'] = 0
dengue_meta_data['Blood_Transmit'] = 1
dengue_meta_data['Airborne'] = 0
dengue_meta_data['Vector_Transmit'] = 1
dengue_meta_data['Droplets_Transmit'] = 0
dengue_meta_data['latent_period_mean'] = np.nan
dengue_meta_data['latent_period_low'] = np.nan
dengue_meta_data['latent_period_high'] = np.nan
dengue_meta_data['incubation_period_mean'] = np.nan
dengue_meta_data['incubation_period_low'] = 5
dengue_meta_data['incubation_period_high'] = 7
dengue_meta_data['average_time_to_death_mean'] = 10.63
dengue_meta_data['average_time_to_death_low'] = 2.196
dengue_meta_data['average_time_to_death_high'] = 19.064
dengue_meta_data['average_time_to_discharge_mean'] = np.nan
dengue_meta_data['average_time_to_discharge_low'] = np.nan
dengue_meta_data['average_time_to_discharge_high'] = np.nan

dengue_meta_data

,Pandemic,Region,Year,Country,Domain,Sub-Domain,LoS_mean,LoS_low,LoS_high,mortality_rate,...,latent_period_high,incubation_period_mean,incubation_period_low,incubation_period_high,average_time_to_death_mean,average_time_to_death_low,average_time_to_death_high,average_time_to_discharge_mean,average_time_to_discharge_low,average_time_to_discharge_high
0,Dengue,AMRO,2000,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
26,Dengue,AMRO,2001,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
78,Dengue,AMRO,2002,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
129,Dengue,AMRO,2003,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
181,Dengue,AMRO,2004,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
233,Dengue,AMRO,2005,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
285,Dengue,AMRO,2006,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
337,Dengue,AMRO,2007,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
389,Dengue,AMRO,2008,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
440,Dengue,AMRO,2009,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
492,Dengue,AMRO,2010,Peru,Iquitos,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
518,Dengue,AMRO,1990,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
553,Dengue,AMRO,1991,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
604,Dengue,AMRO,1992,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
656,Dengue,AMRO,1993,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
708,Dengue,AMRO,1994,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
759,Dengue,AMRO,1995,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
811,Dengue,AMRO,1996,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
863,Dengue,AMRO,1997,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
914,Dengue,AMRO,1998,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
966,Dengue,AMRO,1999,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
1018,Dengue,AMRO,2000,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
1070,Dengue,AMRO,2001,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
1122,Dengue,AMRO,2002,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
1173,Dengue,AMRO,2003,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
1225,Dengue,AMRO,2004,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
1277,Dengue,AMRO,2005,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
1329,Dengue,AMRO,2006,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
1381,Dengue,AMRO,2007,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN
1433,Dengue,AMRO,2008,Puerto Rico,San Juan,NaN,3.46,0.01,6.91,0.2,...,NaN,NaN,5,7,10.63,2.196,19.064,NaN,NaN,NaN

## Ebola

In [59]:
ebola_data = pd.read_csv('F:/Pandemic-Database/Processed_Time_Series_Data/Ebola/Ebola_AFRO_Country_Weekly_CumCases.csv')

ebola_data['Year'] = pd.DatetimeIndex(ebola_data['date']).year
ebola_meta_data = ebola_data[['Region','Year','Country','Domain','Sub-Domain']]
ebola_meta_data = ebola_meta_data.drop_duplicates()

ebola_meta_data.insert(0,'Pandemic', 'Ebola')

ebola_meta_data['LoS_mean'] = np.nan
ebola_meta_data['LoS_low'] = np.nan
ebola_meta_data['LoS_high'] = np.nan
ebola_meta_data['mortality_rate'] = 0.5066
ebola_meta_data['hopitalization_rate_mean'] = np.nan
ebola_meta_data['hopitalization_rate_low'] = np.nan
ebola_meta_data['hopitalization_rate_high'] = np.nan
ebola_meta_data['R0_mean'] = 3.81
ebola_meta_data['R0_low'] = 2.47
ebola_meta_data['R0_high'] = 6.3
ebola_meta_data['Object_Transmit'] = 1
ebola_meta_data['Blood_Transmit'] = 1
ebola_meta_data['Airborne'] = 0
ebola_meta_data['Vector_Transmit'] = 1
ebola_meta_data['Droplets_Transmit'] = 1
ebola_meta_data['latent_period_mean'] = 12.27
ebola_meta_data['latent_period_low'] = 9.42
ebola_meta_data['latent_period_high'] = 15.12
ebola_meta_data['incubation_period_mean'] = 6.22
ebola_meta_data['incubation_period_low'] = 4.65
ebola_meta_data['incubation_period_high'] = 7.79
ebola_meta_data['average_time_to_death_mean'] = 5.33
ebola_meta_data['average_time_to_death_low'] = 1.30
ebola_meta_data['average_time_to_death_high'] = 9.36
ebola_meta_data['average_time_to_discharge_mean'] = 9.4
ebola_meta_data['average_time_to_discharge_low'] = 3.9
ebola_meta_data['average_time_to_discharge_high'] = 14.9

ebola_meta_data

,Pandemic,Region,Year,Country,Domain,Sub-Domain,LoS_mean,LoS_low,LoS_high,mortality_rate,...,latent_period_high,incubation_period_mean,incubation_period_low,incubation_period_high,average_time_to_death_mean,average_time_to_death_low,average_time_to_death_high,average_time_to_discharge_mean,average_time_to_discharge_low,average_time_to_discharge_high
0,Ebola,AFRO,2014,Guinea,NaN,NaN,NaN,NaN,NaN,0.5066,...,15.12,6.22,4.65,7.79,5.33,1.3,9.36,9.4,3.9,14.9
73,Ebola,AFRO,2015,Guinea,NaN,NaN,NaN,NaN,NaN,0.5066,...,15.12,6.22,4.65,7.79,5.33,1.3,9.36,9.4,3.9,14.9
251,Ebola,AFRO,2016,Guinea,NaN,NaN,NaN,NaN,NaN,0.5066,...,15.12,6.22,4.65,7.79,5.33,1.3,9.36,9.4,3.9,14.9
262,Ebola,AFRO,2014,Liberia,NaN,NaN,NaN,NaN,NaN,0.5066,...,15.12,6.22,4.65,7.79,5.33,1.3,9.36,9.4,3.9,14.9
335,Ebola,AFRO,2015,Liberia,NaN,NaN,NaN,NaN,NaN,0.5066,...,15.12,6.22,4.65,7.79,5.33,1.3,9.36,9.4,3.9,14.9
513,Ebola,AFRO,2016,Liberia,NaN,NaN,NaN,NaN,NaN,0.5066,...,15.12,6.22,4.65,7.79,5.33,1.3,9.36,9.4,3.9,14.9
524,Ebola,AFRO,2014,Sierra Leone,NaN,NaN,NaN,NaN,NaN,0.5066,...,15.12,6.22,4.65,7.79,5.33,1.3,9.36,9.4,3.9,14.9
597,Ebola,AFRO,2015,Sierra Leone,NaN,NaN,NaN,NaN,NaN,0.5066,...,15.12,6.22,4.65,7.79,5.33,1.3,9.36,9.4,3.9,14.9
775,Ebola,AFRO,2016,Sierra Leone,NaN,NaN,NaN,NaN,NaN,0.5066,...,15.12,6.22,4.65,7.79,5.33,1.3,9.36,9.4,3.9,14.9

## Monkey Pox

In [60]:
MPox_data = pd.read_csv('F:/Pandemic-Database/Processed_Time_Series_Data/Monkeypox/Mpox_World_Country_Daily_CumCases.csv')

MPox_data['Year'] = pd.DatetimeIndex(MPox_data['date']).year
MPox_meta_data = MPox_data[['Region','Year','Country','Domain','Sub-Domain']]
MPox_meta_data = MPox_meta_data.drop_duplicates()

MPox_meta_data.insert(0,'Pandemic', 'MPox')

MPox_meta_data['LoS_mean'] = 13.3
MPox_meta_data['LoS_low'] = 6.93
MPox_meta_data['LoS_high'] = 19.67
MPox_meta_data['mortality_rate'] = 0.075
MPox_meta_data['hopitalization_rate_mean'] = 0.063
MPox_meta_data['hopitalization_rate_low'] = 0.032
MPox_meta_data['hopitalization_rate_high'] = 0.094
MPox_meta_data['R0_mean'] = 1.75
MPox_meta_data['R0_low'] = 1.10
MPox_meta_data['R0_high'] = 2.40
MPox_meta_data['Object_Transmit'] = 1
MPox_meta_data['Blood_Transmit'] = 0
MPox_meta_data['Airborne'] = 0
MPox_meta_data['Vector_Transmit'] = 0
MPox_meta_data['Droplets_Transmit'] = 1
MPox_meta_data['latent_period_mean'] = 9.40
MPox_meta_data['latent_period_low'] = 3.20
MPox_meta_data['latent_period_high'] = 15.60
MPox_meta_data['incubation_period_mean'] = 6.30
MPox_meta_data['incubation_period_low'] = 0.20
MPox_meta_data['incubation_period_high'] = 12.40
MPox_meta_data['average_time_to_death_mean'] = np.nan
MPox_meta_data['average_time_to_death_low'] = np.nan
MPox_meta_data['average_time_to_death_high'] = np.nan
MPox_meta_data['average_time_to_discharge_mean'] = np.nan
MPox_meta_data['average_time_to_discharge_low'] = np.nan
MPox_meta_data['average_time_to_discharge_high'] = np.nan

MPox_meta_data

,Pandemic,Region,Year,Country,Domain,Sub-Domain,LoS_mean,LoS_low,LoS_high,mortality_rate,...,latent_period_high,incubation_period_mean,incubation_period_low,incubation_period_high,average_time_to_death_mean,average_time_to_death_low,average_time_to_death_high,average_time_to_discharge_mean,average_time_to_discharge_low,average_time_to_discharge_high
0,MPox,EURO,2022,Andorra,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN
160,MPox,EURO,2023,Andorra,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN
438,MPox,AMRO,2022,Argentina,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN
652,MPox,AMRO,2023,Argentina,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN
942,MPox,AMRO,2022,Aruba,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46139,MPox,AMRO,2023,Uruguay,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN
46429,MPox,AMRO,2022,Venezuela,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN
46629,MPox,AMRO,2023,Venezuela,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN
46919,MPox,WPRO,2022,Vietnam,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN
47009,MPox,WPRO,2023,Vietnam,NaN,NaN,13.3,6.93,19.67,0.075,...,15.6,6.3,0.2,12.4,NaN,NaN,NaN,NaN,NaN,NaN

## Zika

In [63]:
zika_data = pd.read_csv('F:/Pandemic-Database/Processed_Time_Series_Data/Zika/Zika_World_Country_Weekly_Cases.csv')

zika_data['Year'] = pd.DatetimeIndex(zika_data['date']).year
zika_meta_data = zika_data[['Region','Year','Country','Domain','Sub-Domain']]
zika_meta_data = zika_meta_data.drop_duplicates()

zika_meta_data.insert(0,'Pandemic', 'Zika')

zika_meta_data['LoS_mean'] = np.nan
zika_meta_data['LoS_low'] = np.nan
zika_meta_data['LoS_high'] = np.nan
zika_meta_data['mortality_rate'] = 0.0526
zika_meta_data['hopitalization_rate_mean'] = 0.03
zika_meta_data['hopitalization_rate_low'] = np.nan
zika_meta_data['hopitalization_rate_high'] = np.nan
zika_meta_data['R0_mean'] = 3.8
zika_meta_data['R0_low'] = 2.5
zika_meta_data['R0_high'] = 5.6
zika_meta_data['Object_Transmit'] = 0
zika_meta_data['Blood_Transmit'] = 1
zika_meta_data['Airborne'] = 0
zika_meta_data['Vector_Transmit'] = 1
zika_meta_data['Droplets_Transmit'] = 0
zika_meta_data['latent_period_mean'] = np.nan
zika_meta_data['latent_period_low'] = np.nan
zika_meta_data['latent_period_high'] = np.nan
zika_meta_data['incubation_period_mean'] = 8.5
zika_meta_data['incubation_period_low'] = 3
zika_meta_data['incubation_period_high'] = 14
zika_meta_data['average_time_to_death_mean'] = np.nan
zika_meta_data['average_time_to_death_low'] = np.nan
zika_meta_data['average_time_to_death_high'] = np.nan
zika_meta_data['average_time_to_discharge_mean'] = np.nan
zika_meta_data['average_time_to_discharge_low'] = np.nan
zika_meta_data['average_time_to_discharge_high'] = np.nan

zika_meta_data

,Pandemic,Region,Year,Country,Domain,Sub-Domain,LoS_mean,LoS_low,LoS_high,mortality_rate,...,latent_period_high,incubation_period_mean,incubation_period_low,incubation_period_high,average_time_to_death_mean,average_time_to_death_low,average_time_to_death_high,average_time_to_discharge_mean,average_time_to_discharge_low,average_time_to_discharge_high
0,Zika,AMRO,2016,Argentina,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN
52,Zika,AMRO,2017,Argentina,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN
84,Zika,AMRO,2016,Brazil,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN
136,Zika,AMRO,2017,Brazil,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN
158,Zika,AMRO,2016,Colombia,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3344,Zika,AMRO,2017,St. Thomas,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN
3376,Zika,AMRO,2016,St. Croix,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN
3428,Zika,AMRO,2017,St. Croix,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN
3460,Zika,AMRO,2016,St. John,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN
3512,Zika,AMRO,2017,St. John,NaN,NaN,NaN,NaN,NaN,0.0526,...,NaN,8.5,3,14,NaN,NaN,NaN,NaN,NaN,NaN

## SARS

In [65]:
SARS_data = pd.read_csv('F:/Pandemic-Database/Processed_Time_Series_Data/SARS/SARS_World_Country_Daily_CumCases.csv')

SARS_data['Year'] = pd.DatetimeIndex(SARS_data['date']).year
SARS_meta_data = SARS_data[['Region','Year','Country','Domain','Sub-Domain']]
SARS_meta_data = SARS_meta_data.drop_duplicates()

SARS_meta_data.insert(0,'Pandemic', 'SARS')

SARS_meta_data['LoS_mean'] = 21
SARS_meta_data['LoS_low'] = np.nan
SARS_meta_data['LoS_high'] = np.nan
SARS_meta_data['mortality_rate'] = 0.11
SARS_meta_data['hopitalization_rate_mean'] = np.nan
SARS_meta_data['hopitalization_rate_low'] = np.nan
SARS_meta_data['hopitalization_rate_high'] = np.nan
SARS_meta_data['R0_mean'] = 2.9
SARS_meta_data['R0_low'] = 2.2
SARS_meta_data['R0_high'] = 3.6
SARS_meta_data['Object_Transmit'] = 1
SARS_meta_data['Blood_Transmit'] = 0
SARS_meta_data['Airborne'] = 1
SARS_meta_data['Vector_Transmit'] = 0
SARS_meta_data['Droplets_Transmit'] = 1
SARS_meta_data['latent_period_mean'] = np.nan
SARS_meta_data['latent_period_low'] = np.nan
SARS_meta_data['latent_period_high'] = np.nan
SARS_meta_data['incubation_period_mean'] = 6.4
SARS_meta_data['incubation_period_low'] = np.nan
SARS_meta_data['incubation_period_high'] = np.nan
SARS_meta_data['average_time_to_death_mean'] = 17.4
SARS_meta_data['average_time_to_death_low'] = np.nan
SARS_meta_data['average_time_to_death_high'] = np.nan
SARS_meta_data['average_time_to_discharge_mean'] = 29.7
SARS_meta_data['average_time_to_discharge_low'] = np.nan
SARS_meta_data['average_time_to_discharge_high'] = np.nan

SARS_meta_data

,Pandemic,Region,Year,Country,Domain,Sub-Domain,LoS_mean,LoS_low,LoS_high,mortality_rate,...,latent_period_high,incubation_period_mean,incubation_period_low,incubation_period_high,average_time_to_death_mean,average_time_to_death_low,average_time_to_death_high,average_time_to_discharge_mean,average_time_to_discharge_low,average_time_to_discharge_high
0,SARS,EURO,2003,Germany,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
1,SARS,AMRO,2003,Canada,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
2,SARS,WPRO,2003,Singapore,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
3,SARS,SEARO,2003,"Hong Kong SAR, China",NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
4,SARS,EURO,2003,Switzerland,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
5,SARS,SEARO,2003,Thailand,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
6,SARS,SEARO,2003,Viet Nam,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
9,SARS,WPRO,2003,China,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
12,SARS,SEARO,2003,"Taiwan, China",NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
15,SARS,EURO,2003,Slovenia,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
16,SARS,EURO,2003,United Kingdom,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
23,SARS,EURO,2003,Spain,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
27,SARS,AMRO,2003,United States,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
46,SARS,EURO,2003,Italy,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
47,SARS,EURO,2003,Republic of Ireland,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
74,SARS,EURO,2003,France,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
123,SARS,EURO,2003,Romania,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
175,SARS,WPRO,2003,Australia,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
176,SARS,EURO,2003,Belgium,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
212,SARS,AMRO,2003,Brazil,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
257,SARS,WPRO,2003,Malaysia,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
331,SARS,EMRO,2003,Kuwait,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
350,SARS,WPRO,2003,Japan,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
356,SARS,AFRO,2003,South Africa,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
391,SARS,SEARO,2003,Indonesia,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
395,SARS,WPRO,2003,Philippines,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
401,SARS,EURO,2003,Sweden,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
463,SARS,SEARO,2003,India,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
469,SARS,WPRO,2003,Mongolia,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
618,SARS,EURO,2003,Bulgaria,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
742,SARS,SEARO,2003,Republic of Korea,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
758,SARS,SEARO,2003,"Macao SAR, China",NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
797,SARS,EURO,2003,Poland,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
824,SARS,WPRO,2003,New Zealand,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
904,SARS,AMRO,2003,Colombia,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
967,SARS,EURO,2003,Finland,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN
1595,SARS,EURO,2003,Russian Federation,NaN,NaN,21,NaN,NaN,0.11,...,NaN,6.4,NaN,NaN,17.4,NaN,NaN,29.7,NaN,NaN

## Influenza

In [69]:
Influenza_data = pd.read_csv('F:/Pandemic-Database/Processed_Time_Series_Data/Influenza/Influenza_World_Domain_Weekly_CumCases.csv')

Influenza_data['Year'] = pd.DatetimeIndex(Influenza_data['date']).year
Influenza_meta_data = Influenza_data[['Region','Year','Country','Domain','Sub-Domain']]
Influenza_meta_data = Influenza_meta_data.drop_duplicates()

Influenza_meta_data.insert(0,'Pandemic', 'Influenza')

Influenza_meta_data['LoS_mean'] = 7.5
Influenza_meta_data['LoS_low'] = 6
Influenza_meta_data['LoS_high'] = 9
Influenza_meta_data['mortality_rate'] = 0.000002
Influenza_meta_data['hopitalization_rate_mean'] = np.nan
Influenza_meta_data['hopitalization_rate_low'] = np.nan
Influenza_meta_data['hopitalization_rate_high'] = np.nan
Influenza_meta_data['R0_mean'] = 1.5
Influenza_meta_data['R0_low'] = 1
Influenza_meta_data['R0_high'] = 2
Influenza_meta_data['Object_Transmit'] = 1
Influenza_meta_data['Blood_Transmit'] = 0
Influenza_meta_data['Airborne'] = 0
Influenza_meta_data['Vector_Transmit'] = 0
Influenza_meta_data['Droplets_Transmit'] = 1
Influenza_meta_data['latent_period_mean'] = np.nan
Influenza_meta_data['latent_period_low'] = np.nan
Influenza_meta_data['latent_period_high'] = np.nan
Influenza_meta_data['incubation_period_mean'] = 2
Influenza_meta_data['incubation_period_low'] = np.nan
Influenza_meta_data['incubation_period_high'] = np.nan
Influenza_meta_data['average_time_to_death_mean'] = np.nan
Influenza_meta_data['average_time_to_death_low'] = np.nan
Influenza_meta_data['average_time_to_death_high'] = np.nan
Influenza_meta_data['average_time_to_discharge_mean'] = np.nan
Influenza_meta_data['average_time_to_discharge_low'] = np.nan
Influenza_meta_data['average_time_to_discharge_high'] = np.nan

Influenza_meta_data

,Pandemic,Region,Year,Country,Domain,Sub-Domain,LoS_mean,LoS_low,LoS_high,mortality_rate,...,latent_period_high,incubation_period_mean,incubation_period_low,incubation_period_high,average_time_to_death_mean,average_time_to_death_low,average_time_to_death_high,average_time_to_discharge_mean,average_time_to_discharge_low,average_time_to_discharge_high
0,Influenza,EURO,2009,Belgium,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Influenza,EMRO,2009,Morocco,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Influenza,EURO,2009,Slovenia,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Influenza,EURO,2009,Austria,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Influenza,EURO,2009,Croatia,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96168,Influenza,EURO,2023,Uzbekistan,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96169,Influenza,WPRO,2023,Vanuatu,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96170,Influenza,WPRO,2023,Vietnam,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96171,Influenza,WPRO,2023,Wallis and Futuna,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101000,Influenza,AFRO,2023,Mozambique,NaN,NaN,7.5,6,9,0.000002,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Combine Data

In [70]:
meta_data_table = pd.concat([covid_meta_data,ebola_meta_data,SARS_meta_data,dengue_meta_data,MPox_meta_data,zika_meta_data,Influenza_meta_data])
meta_data_table = meta_data_table.reset_index(drop = True)
meta_data_table

,Pandemic,Region,Year,Country,Domain,Sub-Domain,LoS_mean,LoS_low,LoS_high,mortality_rate,...,latent_period_high,incubation_period_mean,incubation_period_low,incubation_period_high,average_time_to_death_mean,average_time_to_death_low,average_time_to_death_high,average_time_to_discharge_mean,average_time_to_discharge_low,average_time_to_discharge_high
0,Covid-19,EMRO,2020,Afghanistan,NaN,NaN,NaN,8.26,15.60,0.011000,...,5.9,6.9,6.3,7.5,NaN,2.0,10.0,NaN,NaN,NaN
1,Covid-19,EURO,2020,Albania,NaN,NaN,NaN,9.03,21.59,0.011000,...,5.9,6.9,6.3,7.5,NaN,2.0,10.0,NaN,NaN,NaN
2,Covid-19,AFRO,2020,Algeria,NaN,NaN,NaN,1.00,22.76,0.011000,...,5.9,6.9,6.3,7.5,NaN,2.0,10.0,NaN,NaN,NaN
3,Covid-19,WPRO,2020,American Samoa,NaN,NaN,NaN,15.70,21.12,0.011000,...,5.9,6.9,6.3,7.5,NaN,2.0,10.0,NaN,NaN,NaN
4,Covid-19,EURO,2020,Andorra,NaN,NaN,NaN,9.03,21.59,0.011000,...,5.9,6.9,6.3,7.5,NaN,2.0,10.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3991,Influenza,EURO,2023,Uzbekistan,NaN,NaN,7.5,6.00,9.00,0.000002,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3992,Influenza,WPRO,2023,Vanuatu,NaN,NaN,7.5,6.00,9.00,0.000002,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3993,Influenza,WPRO,2023,Vietnam,NaN,NaN,7.5,6.00,9.00,0.000002,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3994,Influenza,WPRO,2023,Wallis and Futuna,NaN,NaN,7.5,6.00,9.00,0.000002,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3995,Influenza,AFRO,2023,Mozambique,NaN,NaN,7.5,6.00,9.00,0.000002,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
meta_data_table.to_csv("F:/Pandemic-Database/Meta_Data/past_pandemic_metadata.csv",
                      index = 'False')